# One-time state migration: the org, OUs, accounts, and SCPs moved to the
# accounts/ root. Each block drops the resource from THIS state without touching
# the real object (destroy = false); accounts/ adopts it through import blocks
# generated by scripts/migrate-accounts-state.sh. Run that import first, then
# apply this root. Safe to delete these blocks once both applies have run.

removed {
  from = aws_organizations_organization.org

  lifecycle {
    destroy = false
  }
}

removed {
  from = aws_organizations_organizational_unit.security

  lifecycle {
    destroy = false
  }
}

removed {
  from = aws_organizations_organizational_unit.infrastructure

  lifecycle {
    destroy = false
  }
}

removed {
  from = aws_organizations_organizational_unit.sandbox

  lifecycle {
    destroy = false
  }
}

removed {
  from = aws_organizations_organizational_unit.workloads

  lifecycle {
    destroy = false
  }
}

removed {
  from = aws_organizations_organizational_unit.dev

  lifecycle {
    destroy = false
  }
}

removed {
  from = aws_organizations_organizational_unit.test

  lifecycle {
    destroy = false
  }
}

removed {
  from = aws_organizations_organizational_unit.prod

  lifecycle {
    destroy = false
  }
}

removed {
  from = aws_organizations_account.sandbox

  lifecycle {
    destroy = false
  }
}

removed {
  from = aws_organizations_account.dev

  lifecycle {
    destroy = false
  }
}

removed {
  from = aws_organizations_account.test

  lifecycle {
    destroy = false
  }
}

removed {
  from = aws_organizations_account.prod

  lifecycle {
    destroy = false
  }
}

removed {
  from = aws_organizations_account.security

  lifecycle {
    destroy = false
  }
}

removed {
  from = aws_organizations_account.network

  lifecycle {
    destroy = false
  }
}

removed {
  from = aws_organizations_account.shared_services

  lifecycle {
    destroy = false
  }
}

removed {
  from = aws_organizations_account.log_archive

  lifecycle {
    destroy = false
  }
}

removed {
  from = aws_organizations_policy.deny_leave_org

  lifecycle {
    destroy = false
  }
}

removed {
  from = aws_organizations_policy.deny_root_user

  lifecycle {
    destroy = false
  }
}

removed {
  from = aws_organizations_policy.region_lockdown

  lifecycle {
    destroy = false
  }
}

removed {
  from = aws_organizations_policy.require_s3_encryption

  lifecycle {
    destroy = false
  }
}

removed {
  from = aws_organizations_policy.deny_cloudtrail_tampering

  lifecycle {
    destroy = false
  }
}

removed {
  from = aws_organizations_policy.deny_public_s3

  lifecycle {
    destroy = false
  }
}

removed {
  from = aws_organizations_policy.deny_disable_detective

  lifecycle {
    destroy = false
  }
}

removed {
  from = aws_organizations_policy.tag_policy

  lifecycle {
    destroy = false
  }
}

removed {
  from = aws_organizations_policy_attachment.root_deny_leave_org

  lifecycle {
    destroy = false
  }
}

removed {
  from = aws_organizations_policy_attachment.root_deny_root_user

  lifecycle {
    destroy = false
  }
}

removed {
  from = aws_organizations_policy_attachment.root_deny_disable_detective

  lifecycle {
    destroy = false
  }
}

removed {
  from = aws_organizations_policy_attachment.infrastructure_region_lockdown

  lifecycle {
    destroy = false
  }
}

removed {
  from = aws_organizations_policy_attachment.infrastructure_require_s3_encryption

  lifecycle {
    destroy = false
  }
}

removed {
  from = aws_organizations_policy_attachment.sandbox_region_lockdown

  lifecycle {
    destroy = false
  }
}

removed {
  from = aws_organizations_policy_attachment.workloads_region_lockdown

  lifecycle {
    destroy = false
  }
}

removed {
  from = aws_organizations_policy_attachment.workloads_require_s3_encryption

  lifecycle {
    destroy = false
  }
}

removed {
  from = aws_organizations_policy_attachment.prod_deny_cloudtrail_tampering

  lifecycle {
    destroy = false
  }
}

removed {
  from = aws_organizations_policy_attachment.prod_deny_public_s3

  lifecycle {
    destroy = false
  }
}

removed {
  from = aws_organizations_policy_attachment.root_tag_policy

  lifecycle {
    destroy = false
  }
}
