#!/usr/bin/env bash
#
# migrate-accounts-state.sh: one-time move of the org, OUs, member accounts, and
# SCPs from the governance root's state into the persistent accounts/ root.
#
# It reads the governance state and writes accounts/migrate_imports.tf, one
# import block per aws_organizations_* resource, keyed by the same address. The
# file is gitignored so account ids stay out of the repo. Nothing is applied
# here; the operator reviews and applies each plan.
#
# Order:
#   1. scripts/migrate-accounts-state.sh
#   2. terraform -chdir=accounts init && terraform -chdir=accounts plan -out=tfplan
#      (expect N to import, 0 to add, 0 to destroy; close_on_deletion updates in place)
#   3. terraform -chdir=accounts apply tfplan
#   4. terraform -chdir=terraform plan -out=tfplan
#      (expect the same N "removed from state, not destroyed", nothing else)
#   5. terraform -chdir=terraform apply tfplan
#   6. rm accounts/migrate_imports.tf

export AWS_PAGER=""
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/accounts/migrate_imports.tf"

if terraform -chdir="$ROOT/accounts" state list 2>/dev/null | grep -q .; then
  echo "migrate-accounts-state: accounts/ state is not empty; migration already ran." >&2
  exit 1
fi

json="$(terraform -chdir="$ROOT/terraform" show -json)"

{
  echo "# GENERATED by scripts/migrate-accounts-state.sh. Gitignored; delete after apply."
  echo "$json" | jq -r '
    .values.root_module.resources[]?
    | select(.mode == "managed" and (.type | startswith("aws_organizations_")))
    | "\nimport {\n  to = \(.address)\n  id = \"\(.values.id)\"\n}"'
} >"$OUT"

count="$(grep -c '^import {' "$OUT" || true)"
if [[ "$count" -eq 0 ]]; then
  rm -f "$OUT"
  echo "migrate-accounts-state: no aws_organizations_* resources in governance state; nothing to move." >&2
  exit 1
fi

terraform -chdir="$ROOT/accounts" fmt "$OUT" >/dev/null
echo "migrate-accounts-state: wrote $count import blocks to accounts/migrate_imports.tf"
echo "Next: terraform -chdir=accounts init && terraform -chdir=accounts plan -out=tfplan"
